In [1]:
import keras
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn import datasets
import tensorflow_hub as hub
from PIL import Image, ImageDraw, ImageFont
from os import path, listdir
from pathlib import Path
import cv2 as cv


%matplotlib inline

!git clone https://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@github.com/POE-DAMERON/Glie-44.git

Cloning into 'Glie-44'...
remote: Enumerating objects: 14, done.
remote: Counting objects: 100% (14/14), done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 1583 (delta 3), reused 7 (delta 1), pack-reused 1569
Receiving objects: 100% (1583/1583), 278.18 MiB | 26.49 MiB/s, done.
Resolving deltas: 100% (21/21), done.
Checking out files: 100% (1502/1502), done.


In [2]:
class Utils():

  @staticmethod
  def add_blocks(pred, draw, height, width, font_path, precision):
    boxes = pred['detection_boxes'].numpy()[0]
    classes = pred['detection_classes'].numpy()[0]

    boxes[:, 0] *= height
    boxes[:, 1] *= width
    boxes[:, 2] *= height
    boxes[:, 3] *= width
    
    for i in range(len(boxes)):
      if pred['detection_scores'].numpy()[0][i] > precision:
        draw.rectangle(Utils.prepare_coords(boxes[i]), outline = Utils.which_color(classes[i]), width = 3)
        draw.text((boxes[i][1], boxes[i][0]),str(classes[i])[:-2], fill=(255,255,255), stroke_fill= (0,0,0,255), stroke_width = 2, font= ImageFont.truetype(font_path, 20))

  @staticmethod
  def which_color(class_id):
    color_value = int(class_id) * 9
    return (min(color_value, 255), max(min(color_value - 255, 255),0),max(min(color_value - 256 * 2 - 1, 255),0))

  @staticmethod
  def prepare_coords(array):
    return (array[1], array[0], array[3], array[2])

In [5]:
class Glie_44():

  def __init__(self, precision = .2, font_path = Path().absolute().joinpath('Glie-44/Model/Data/fonts/Roboto-Regular.ttf')):
    self.__precision = precision
    self.__font_path = str(font_path)


  def set_font_path(self, font_path):
    self.__font_path = font_path


  def load_model(self):
    self.__model = hub.load("https://tfhub.dev/tensorflow/ssd_mobilenet_v2/2")


  def set_model(self,model):
    self.__model = model

  def pred(self, image_data):
    return self.__model(image_data)

  def pred_on_image(self, image_path):
    image_data = plt.imread(image_path)
    image_data = np.array([image_data])

    return self.pred(image_data)

  def run_on_image(self, image_path):
    pred = pred_on_image(image_path)

    image = Image.open(image_path)
    draw = ImageDraw.Draw(image)
    Utils.add_blocks(pred,draw, image_data.shape[1], image_data.shape[2], self.__font_path, self.__precision)

    return np.array(image)

  # Takes a folder path where the images should be in chronological order to 
  # detect and compile in a video

  def run_on_folder(self, folder_path = Path().absolute().joinpath('Glie-44/Model/Data/VisDrone2019-MOT-train/sequences/uav0000013_00000_v'), output_folder = Path().absolute().joinpath('Glie-44/Model/outputs')):

    video_frames = sorted(listdir(folder_path))
    s = Image.open(Path(folder_path).joinpath(video_frames[0])).size

    output_path = path.basename(folder_path) + '.avi'
    fourcc = cv.VideoWriter_fourcc(*'DIVX')
    writer = cv.VideoWriter(str(output_folder) + '/' + output_path, fourcc, 20, s)

    sample = video_frames
    total_frames = len(sample)
    for i in range(total_frames):
      #print(i + 1, '/', total_frames)
      result = self.run_on_image(Path(folder_path).joinpath(sample[i]))
      #print(sample[i], ':', result.shape)
      writer.write(cv.cvtColor(result,cv.COLOR_RGB2BGR))

    writer.release()

    # Takes a video file to detect objects

  def run_on_video():
    pass

  #  takes a video stream and outputs a video stream with the boxes around the
  #  detected objects

  def run_on_stream():
    pass

In [6]:
model2 = hub.load("https://tfhub.dev/tensorflow/ssd_mobilenet_v2/2")

KeyboardInterrupt: ignored

In [9]:
glie = Glie_44()
glie.set_model(test)

"""
    TO TEST THE RUN_ON_IMAGE

pred_image = glie.run_on_image('Glie-44/Model/Data/VisDrone2019-MOT-train/sequences/uav0000013_01073_v/0000001.jpg')
plt.figure(figsize=(24,32))
plt.imshow(pred_image)

"""
pred = glie.pred_on_image('Glie-44/Model/Data/VisDrone2019-MOT-train/sequences/uav0000013_01073_v/0000001.jpg')
pred
#glie.run_on_folder(folder_path='Glie-44/Model/Data/VisDrone2019-MOT-train/sequences/uav0000013_00000_v')

{'detection_anchor_indices': <tf.Tensor: shape=(1, 100), dtype=float32, numpy=
 array([[ 486.,  489.,  621.,  444.,  678.,  144., 1731., 1862.,  387.,
          978.,  261.,  198.,  141.,  258.,  981.,  546.,  255.,  369.,
          735.,  813.,  201.,  825., 1868.,  483.,  147.,  543.,  318.,
         1725.,  770.,  546.,  252.,  675.,  384.,  492.,  828.,  546.,
          711.,  144.,  309.,  195.,  735.,  147.,  564.,  432.,  618.,
          651.,  654.,  138., 1239.,  249.,  546.,  312.,  441.,  426.,
           87.,  543., 1053., 1796.,  204.,  306., 1784.,  366.,  711.,
          144.,  768.,  885.,  501.,  369.,  489.,   84.,   84.,  735.,
          546.,  429.,  597., 1859.,  444.,  543.,  929.,  540.,   90.,
          147.,  597., 1761., 1227.,  546., 1724.,  678.,  885., 1173.,
           87.,  327., 1796.,  546.,  600., 1289.,  192., 1844.,  201.,
          144.]], dtype=float32)>,
 'detection_boxes': <tf.Tensor: shape=(1, 100, 4), dtype=float32, numpy=
 array([[[0.38539416,

In [2]:
test = hub.KerasLayer("https://tfhub.dev/tensorflow/ssd_mobilenet_v2/2", trainable=False)

In [85]:
import tensorflow as tf

x = np.array(Image.open('Glie-44/Model/Data/VisDrone2019-MOT-train/sequences/uav0000013_01073_v/0000001.jpg'))
shape = x.shape
x = np.array([x])

initial_layer = tf.keras.Input(shape=shape, name="initial_layer",dtype=tf.uint8)
layer = test(initial_layer)['raw_detection_scores']
#print(layer)
layer = tf.keras.layers.Flatten()(layer)
layer = tf.keras.layers.Dense(1000, activation='relu',)(layer)
last_layer = tf.keras.layers.Dense(10, activation='softmax')(layer)

model = keras.Model(initial_layer, last_layer)


model.compile(optimizer="adam", metrics=['accuracy'], loss='categorical_crossentropy')
model.summary()

model.fit(x=x, y=np.ones((1,10)), batch_size=2, epochs = 2)





Model: "model_30"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
initial_layer (InputLayer)   [(None, 756, 1344, 3)]    0         
_________________________________________________________________
keras_layer (KerasLayer)     {'raw_detection_scores':  0         
_________________________________________________________________
flatten_1 (Flatten)          (1, 174447)               0         
_________________________________________________________________
dense_73 (Dense)             (1, 1000)                 174448000 
_________________________________________________________________
dense_74 (Dense)             (1, 10)                   10010     
Total params: 174,458,010
Trainable params: 174,458,010
Non-trainable params: 0
_________________________________________________________________
Epoch 1/2


/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/indexed_slices.py:437: UserWarning: Converting sparse IndexedSlices(IndexedSlices(indices=Tensor("gradients/Postprocessor/BatchMultiClassNonMaxSuppression/MultiClassNonMaxSuppression/Gather_90/GatherV2_6_grad/Reshape_1:0", shape=(None,), dtype=int32), values=Tensor("gradients/Postprocessor/BatchMultiClassNonMaxSuppression/MultiClassNonMaxSuppression/ChangeCoordinateFrame/Scale/concat_grad/Slice_1:0", shape=(None, None), dtype=float32), dense_shape=Tensor("gradients/Postprocessor/BatchMultiClassNonMaxSuppression/MultiClassNonMaxSuppression/ChangeCoordinateFrame/Scale/concat_grad/Shape:0", shape=(2,), dtype=int32))) to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "shape. This may consume a large amount of memory." % value)
/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/indexed_slices.py:437: UserWarning: Converting sparse IndexedSlices(IndexedSlices(indices=Tensor("grad

StagingError: ignored

In [67]:
np.ones((1,10,10))

array([[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]])